 FUNCTION GET_DAY_STRING, STDAY
;===============================================

  IF STDAY LT 10 THEN $
   STRING_START = '00' + STRTRIM( STRING(STDAY,'(I1)') ) $
  ELSE IF STDAY GE 10 AND STDAY LT 100 THEN $
   STRING_START =  '0' + STRTRIM( STRING(STDAY,'(I2)') ) $
  ELSE $
   STRING_START = STRTRIM( STRING(STDAY,'(I3)') )

  RETURN, STRING_START
  END
